In [45]:
import pandas as pd

## Описание признаков

- kolesa_id - уникальный id объявления со стороны сервиса
- kolesa_url - ссылка на объявление
- parsed_at - дата и время получения объявления
- brand - марка авто
- model - модель авто
- generation - поколение данного авто (этой марки)
- year - год выпуска авто
- city - город публикации объявление
- body_type - тип кузова авто
- fuel_type - тип топлива
- engine_volume - объем двигателя
- mileage - пробег в км
- transmission - тип коробки/трансмиссии
- drive_type - тип привода
- steering_wheel - расположение руля
- color - цвет авто    
- kz_registration - растаможен ли в Казахстане
- imgs_count - количество фотографий в объявлении
- price - цена продажи
- img_filename - название файла с главным фото объявления
- img_url - ссылка на на главное фото объявления
- found_img - нашли ли фото

Из них технические: kolesa_id, kolesa_url, parsed_at, img_filename, img_url, found_img

Все остальные могут быть рассмотрены для решения задачи DL на табличных данных

In [46]:
df = pd.read_csv('fourth_df.csv')
df

,kolesa_id,kolesa_url,parsed_at,brand,model,generation,year,city,body_type,fuel_type,...,transmission,drive_type,steering_wheel,color,kz_registration,imgs_count,price,img_filename,img_url,found_img
0,220599328,https://kolesa.kz/a/show/220599328?search_id=f...,2026-06-11 12:11:47.553405+03:00,Chevrolet,Cobalt,2011 - н.в. 2 поколение\n,2021,"\n Астана, ...",Седан\n,бензин,...,Автомат\n,Передний привод\n,Слева\n,\n черн...,Да\n,25,4490000,220599328.webp,https://kolesa-photos.kcdn.online/webp/de/de4f...,True
1,222486528,https://kolesa.kz/a/show/222486528?search_id=f...,2026-06-11 12:11:59.858484+03:00,Chevrolet,Monza,2022 - н.в. 2 поколение рестайлинг\n,2023,"\n Астана, ...",Седан\n,бензин,...,Робот\n,Передний привод\n,Слева\n,\n серы...,Да\n,6,6400000,222486528.webp,https://kolesa-photos.kcdn.online/webp/c1/c19d...,True
2,218695550,https://kolesa.kz/a/show/218695550?search_id=f...,2026-06-11 12:12:12.664183+03:00,Chevrolet,Captiva,2018 - н.в. 2 поколение\n,2021,"\n Алматы, ...",Внедорожник\n,бензин,...,Автомат\n,Передний привод\n,Слева\n,\n серы...,Да\n,27,7150000,218695550.webp,https://kolesa-photos.kcdn.online/webp/55/5518...,True
3,220471159,https://kolesa.kz/a/show/220471159?search_id=f...,2026-06-11 12:12:28.093064+03:00,Chevrolet,Cruze,2012 - 2015 J300 рестайлинг\n,2013,"\n Алматы, ...",Хэтчбек\n,бензин,...,Автомат\n,Передний привод\n,Слева\n,\n сере...,Да\n,8,4400000,220471159.webp,https://kolesa-photos.kcdn.online/webp/bb/bb26...,True
4,214781208,https://kolesa.kz/a/show/214781208?search_id=f...,2026-06-11 12:12:44.777117+03:00,Chevrolet,Aveo,2006 - 2012 T250 рестайлинг (T250/T255)\n,2007,"\n Астана, ...",Седан\n,бензин,...,Автомат\n,Передний привод\n,Слева\n,NaN,Да\n,10,2450000,214781208.webp,https://kolesa-photos.kcdn.online/webp/bb/bb06...,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5391,222704181,https://kolesa.kz/a/show/222704181?search_id=6...,2026-06-11 01:33:57.011643+03:00,Hyundai,Grandeur,2011 - 2016 HG\n,2011,"\n Шымкент,...",Седан\n,бензин,...,Автомат\n,Передний привод\n,Слева\n,\n белы...,Да\n,24,8300000,222704181.webp,https://kolesa-photos.kcdn.online/webp/d6/d6c9...,True
5392,220000872,https://kolesa.kz/a/show/220000872?search_id=6...,2026-06-11 01:34:13.055741+03:00,Hyundai,Sonata,2019 - н.в. 8 поколение (DN8)\n,2022,"\n Атырау, ...",Седан\n,бензин,...,Автомат\n,Передний привод\n,Слева\n,NaN,Да\n,11,12500000,220000872.webp,https://kolesa-photos.kcdn.online/webp/22/2242...,True
5393,222682662,https://kolesa.kz/a/show/222682662?search_id=6...,2026-06-11 01:34:37.636103+03:00,Hyundai,i30,2020 - н.в. 3 поколение рестайлинг (PD)\n,2023,"\n Шымкент,...",Универсал\n,бензин,...,Автомат\n,Передний привод\n,Слева\n,\n белы...,Да\n,10,9000000,222682662.webp,https://kolesa-photos.kcdn.online/webp/7b/7b0f...,True
5394,222542135,https://kolesa.kz/a/show/222542135?search_id=6...,2026-06-11 01:34:52.986032+03:00,Hyundai,Elantra,2018 - 2020 6 поколение рестайлинг (AD/ADA)\n,2018,"\n Уральск,...",Седан\n,бензин,...,Автомат\n,Передний привод\n,Слева\n,NaN,Да\n,19,6200000,222542135.webp,https://kolesa-photos.kcdn.online/webp/9e/9ef9...,True
5395,220019907,https://kolesa.kz/a/show/220019907?search_id=6...,2026-06-11 01:35:29.695414+03:00,Hyundai,Tucson,2018 - 2021 3 поколение рестайлинг (TL/TLE)\n,2018,"\n Актобе, ...",Кроссовер\n,бензин,...,Автомат\n,Передний привод\n,Слева\n,NaN,Да\n,21,9900000,220019907.webp,https://kolesa-photos.kcdn.online/webp/0c/0c61...,True

In [47]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5396 entries, 0 to 5395
Data columns (total 22 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   kolesa_id        5396 non-null   int64
 1   kolesa_url       5396 non-null   str
 2   parsed_at        5396 non-null   str
 3   brand            5396 non-null   str
 4   model            5396 non-null   str
 5   generation       5390 non-null   str
 6   year             5396 non-null   int64
 7   city             5396 non-null   str
 8   body_type        5396 non-null   str
 9   fuel_type        5396 non-null   str
 10  engine_volume    5396 non-null   float64
 11  mileage          5396 non-null   int64
 12  transmission     5396 non-null   str
 13  drive_type       5396 non-null   str
 14  steering_wheel   5396 non-null   str
 15  color            3959 non-null   str
 16  kz_registration  5396 non-null   str
 17  imgs_count       5396 non-null   int64
 18  price            5396 non-null   int64
 19  img_filename     5376 non-null   str
 20  img_url          5376 non-null   str
 21  found_img        5396 non-null   bool
dtypes: bool(1), float64(1), int64(5), str(15)
memory usage: 890.7 KB

## Подгтовим данные для дальнейшей работы

Общая проверка на пропуски

In [48]:
df.isna().sum()

kolesa_id             0
kolesa_url            0
parsed_at             0
brand                 0
model                 0
generation            6
year                  0
city                  0
body_type             0
fuel_type             0
engine_volume         0
mileage               0
transmission          0
drive_type            0
steering_wheel        0
color              1437
kz_registration       0
imgs_count            0
price                 0
img_filename         20
img_url              20
found_img             0
dtype: int64

Основная проблема - пропуски в color. Это было обнаружено еще в ходе парсинга. Заполним их значением 

Пропуски в img_filename и img_url мы будем отдельно обрабатывать позже

In [49]:
df['color'] = df['color'].fillna('unknown')

### City, body_type, transmission, drive_type, steering_wheel, color, kz_registration

In [50]:
df[['city', 'body_type', 'transmission', 'drive_type', 'steering_wheel', 'color', 'kz_registration']]

,city,body_type,transmission,drive_type,steering_wheel,color,kz_registration
0,"\n Астана, ...",Седан\n,Автомат\n,Передний привод\n,Слева\n,\n черн...,Да\n
1,"\n Астана, ...",Седан\n,Робот\n,Передний привод\n,Слева\n,\n серы...,Да\n
2,"\n Алматы, ...",Внедорожник\n,Автомат\n,Передний привод\n,Слева\n,\n серы...,Да\n
3,"\n Алматы, ...",Хэтчбек\n,Автомат\n,Передний привод\n,Слева\n,\n сере...,Да\n
4,"\n Астана, ...",Седан\n,Автомат\n,Передний привод\n,Слева\n,unknown,Да\n
...,...,...,...,...,...,...,...
5391,"\n Шымкент,...",Седан\n,Автомат\n,Передний привод\n,Слева\n,\n белы...,Да\n
5392,"\n Атырау, ...",Седан\n,Автомат\n,Передний привод\n,Слева\n,unknown,Да\n
5393,"\n Шымкент,...",Универсал\n,Автомат\n,Передний привод\n,Слева\n,\n белы...,Да\n
5394,"\n Уральск,...",Седан\n,Автомат\n,Передний привод\n,Слева\n,unknown,Да\n
5395,"\n Актобе, ...",Кроссовер\n,Автомат\n,Передний привод\n,Слева\n,unknown,Да\n

Все это признаки, содержащие текст

Заметим, что у нас не убраны символы переноса строк \n и, возможно, лишние пробелы

Уберем это у всех этих признаков

In [51]:
df['city'] = df['city'].apply(lambda x: x.replace('\n', '').strip())
df['body_type'] = df['body_type'].apply(lambda x: x.replace('\n', '').strip())
df['transmission'] = df['transmission'].apply(lambda x: x.replace('\n', '').strip())
df['drive_type'] = df['drive_type'].apply(lambda x: x.replace('\n', '').strip())
df['steering_wheel'] = df['steering_wheel'].apply(lambda x: x.replace('\n', '').strip())
df['color'] = df['color'].apply(lambda x: x.replace('\n', '').strip())
df['kz_registration'] = df['kz_registration'].apply(lambda x: x.replace('\n', '').strip())

In [52]:
df[['city', 'body_type', 'transmission', 'drive_type', 'steering_wheel', 'color', 'kz_registration']]

,city,body_type,transmission,drive_type,steering_wheel,color,kz_registration
0,"Астана, Акмолинская область",Седан,Автомат,Передний привод,Слева,черный,Да
1,"Астана, Акмолинская область",Седан,Робот,Передний привод,Слева,серый металлик,Да
2,"Алматы, Алматинская область",Внедорожник,Автомат,Передний привод,Слева,серый,Да
3,"Алматы, Алматинская область",Хэтчбек,Автомат,Передний привод,Слева,серебристый,Да
4,"Астана, Акмолинская область",Седан,Автомат,Передний привод,Слева,unknown,Да
...,...,...,...,...,...,...,...
5391,"Шымкент, Туркестанская область",Седан,Автомат,Передний привод,Слева,белый,Да
5392,"Атырау, Атырауская область",Седан,Автомат,Передний привод,Слева,unknown,Да
5393,"Шымкент, Туркестанская область",Универсал,Автомат,Передний привод,Слева,белый металлик,Да
5394,"Уральск, Западно-Казахстанская область",Седан,Автомат,Передний привод,Слева,unknown,Да
5395,"Актобе, Актюбинская область",Кроссовер,Автомат,Передний привод,Слева,unknown,Да

In [53]:
df.to_csv('clean_df.csv', index=False)

In [54]:
df_table = df.copy()
df_table = df_table.drop(columns=['kolesa_id', 'kolesa_url', 'parsed_at', 'img_filename', 'img_url', 'found_img'])
df_table.info()

<class 'pandas.DataFrame'>
RangeIndex: 5396 entries, 0 to 5395
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   brand            5396 non-null   str
 1   model            5396 non-null   str
 2   generation       5390 non-null   str
 3   year             5396 non-null   int64
 4   city             5396 non-null   str
 5   body_type        5396 non-null   str
 6   fuel_type        5396 non-null   str
 7   engine_volume    5396 non-null   float64
 8   mileage          5396 non-null   int64
 9   transmission     5396 non-null   str
 10  drive_type       5396 non-null   str
 11  steering_wheel   5396 non-null   str
 12  color            5396 non-null   str
 13  kz_registration  5396 non-null   str
 14  imgs_count       5396 non-null   int64
 15  price            5396 non-null   int64
dtypes: float64(1), int64(4), str(11)
memory usage: 674.6 KB