### Датасет для задачи на табличных данных

In [42]:
import pandas as pd

In [43]:
df = pd.read_csv('clean_df.csv')
df = df[df['found_img'] == True]
df

,kolesa_id,kolesa_url,parsed_at,brand,model,generation,year,city,body_type,fuel_type,...,transmission,drive_type,steering_wheel,color,kz_registration,imgs_count,price,img_filename,img_url,found_img
0,220599328,https://kolesa.kz/a/show/220599328?search_id=f...,2026-06-11 12:11:47.553405+03:00,Chevrolet,Cobalt,2011 - н.в. 2 поколение\n,2021,"Астана, Акмолинская область",Седан,бензин,...,Автомат,Передний привод,Слева,черный,Да,25,4490000,220599328.webp,https://kolesa-photos.kcdn.online/webp/de/de4f...,True
1,222486528,https://kolesa.kz/a/show/222486528?search_id=f...,2026-06-11 12:11:59.858484+03:00,Chevrolet,Monza,2022 - н.в. 2 поколение рестайлинг\n,2023,"Астана, Акмолинская область",Седан,бензин,...,Робот,Передний привод,Слева,серый металлик,Да,6,6400000,222486528.webp,https://kolesa-photos.kcdn.online/webp/c1/c19d...,True
2,218695550,https://kolesa.kz/a/show/218695550?search_id=f...,2026-06-11 12:12:12.664183+03:00,Chevrolet,Captiva,2018 - н.в. 2 поколение\n,2021,"Алматы, Алматинская область",Внедорожник,бензин,...,Автомат,Передний привод,Слева,серый,Да,27,7150000,218695550.webp,https://kolesa-photos.kcdn.online/webp/55/5518...,True
3,220471159,https://kolesa.kz/a/show/220471159?search_id=f...,2026-06-11 12:12:28.093064+03:00,Chevrolet,Cruze,2012 - 2015 J300 рестайлинг\n,2013,"Алматы, Алматинская область",Хэтчбек,бензин,...,Автомат,Передний привод,Слева,серебристый,Да,8,4400000,220471159.webp,https://kolesa-photos.kcdn.online/webp/bb/bb26...,True
4,214781208,https://kolesa.kz/a/show/214781208?search_id=f...,2026-06-11 12:12:44.777117+03:00,Chevrolet,Aveo,2006 - 2012 T250 рестайлинг (T250/T255)\n,2007,"Астана, Акмолинская область",Седан,бензин,...,Автомат,Передний привод,Слева,unknown,Да,10,2450000,214781208.webp,https://kolesa-photos.kcdn.online/webp/bb/bb06...,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5391,222704181,https://kolesa.kz/a/show/222704181?search_id=6...,2026-06-11 01:33:57.011643+03:00,Hyundai,Grandeur,2011 - 2016 HG\n,2011,"Шымкент, Туркестанская область",Седан,бензин,...,Автомат,Передний привод,Слева,белый,Да,24,8300000,222704181.webp,https://kolesa-photos.kcdn.online/webp/d6/d6c9...,True
5392,220000872,https://kolesa.kz/a/show/220000872?search_id=6...,2026-06-11 01:34:13.055741+03:00,Hyundai,Sonata,2019 - н.в. 8 поколение (DN8)\n,2022,"Атырау, Атырауская область",Седан,бензин,...,Автомат,Передний привод,Слева,unknown,Да,11,12500000,220000872.webp,https://kolesa-photos.kcdn.online/webp/22/2242...,True
5393,222682662,https://kolesa.kz/a/show/222682662?search_id=6...,2026-06-11 01:34:37.636103+03:00,Hyundai,i30,2020 - н.в. 3 поколение рестайлинг (PD)\n,2023,"Шымкент, Туркестанская область",Универсал,бензин,...,Автомат,Передний привод,Слева,белый металлик,Да,10,9000000,222682662.webp,https://kolesa-photos.kcdn.online/webp/7b/7b0f...,True
5394,222542135,https://kolesa.kz/a/show/222542135?search_id=6...,2026-06-11 01:34:52.986032+03:00,Hyundai,Elantra,2018 - 2020 6 поколение рестайлинг (AD/ADA)\n,2018,"Уральск, Западно-Казахстанская область",Седан,бензин,...,Автомат,Передний привод,Слева,unknown,Да,19,6200000,222542135.webp,https://kolesa-photos.kcdn.online/webp/9e/9ef9...,True
5395,220019907,https://kolesa.kz/a/show/220019907?search_id=6...,2026-06-11 01:35:29.695414+03:00,Hyundai,Tucson,2018 - 2021 3 поколение рестайлинг (TL/TLE)\n,2018,"Актобе, Актюбинская область",Кроссовер,бензин,...,Автомат,Передний привод,Слева,unknown,Да,21,9900000,220019907.webp,https://kolesa-photos.kcdn.online/webp/0c/0c61...,True

Оставим только нужные, для задачи на табличных данных, колонки

In [44]:
df_table = df.copy()
df_table = df_table.drop(columns=['kolesa_id', 'kolesa_url', 'parsed_at', 'img_filename', 'img_url', 'found_img'])
df_table

,brand,model,generation,year,city,body_type,fuel_type,engine_volume,mileage,transmission,drive_type,steering_wheel,color,kz_registration,imgs_count,price
0,Chevrolet,Cobalt,2011 - н.в. 2 поколение\n,2021,"Астана, Акмолинская область",Седан,бензин,1.5,145113,Автомат,Передний привод,Слева,черный,Да,25,4490000
1,Chevrolet,Monza,2022 - н.в. 2 поколение рестайлинг\n,2023,"Астана, Акмолинская область",Седан,бензин,1.5,20000,Робот,Передний привод,Слева,серый металлик,Да,6,6400000
2,Chevrolet,Captiva,2018 - н.в. 2 поколение\n,2021,"Алматы, Алматинская область",Внедорожник,бензин,1.5,85024,Автомат,Передний привод,Слева,серый,Да,27,7150000
3,Chevrolet,Cruze,2012 - 2015 J300 рестайлинг\n,2013,"Алматы, Алматинская область",Хэтчбек,бензин,1.8,146000,Автомат,Передний привод,Слева,серебристый,Да,8,4400000
4,Chevrolet,Aveo,2006 - 2012 T250 рестайлинг (T250/T255)\n,2007,"Астана, Акмолинская область",Седан,бензин,1.4,216000,Автомат,Передний привод,Слева,unknown,Да,10,2450000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5391,Hyundai,Grandeur,2011 - 2016 HG\n,2011,"Шымкент, Туркестанская область",Седан,бензин,3.0,148000,Автомат,Передний привод,Слева,белый,Да,24,8300000
5392,Hyundai,Sonata,2019 - н.в. 8 поколение (DN8)\n,2022,"Атырау, Атырауская область",Седан,бензин,2.5,110000,Автомат,Передний привод,Слева,unknown,Да,11,12500000
5393,Hyundai,i30,2020 - н.в. 3 поколение рестайлинг (PD)\n,2023,"Шымкент, Туркестанская область",Универсал,бензин,1.5,45000,Автомат,Передний привод,Слева,белый металлик,Да,10,9000000
5394,Hyundai,Elantra,2018 - 2020 6 поколение рестайлинг (AD/ADA)\n,2018,"Уральск, Западно-Казахстанская область",Седан,бензин,2.0,136197,Автомат,Передний привод,Слева,unknown,Да,19,6200000
5395,Hyundai,Tucson,2018 - 2021 3 поколение рестайлинг (TL/TLE)\n,2018,"Актобе, Актюбинская область",Кроссовер,бензин,2.0,84000,Автомат,Передний привод,Слева,unknown,Да,21,9900000

In [45]:
df_table.info()

<class 'pandas.DataFrame'>
Index: 5296 entries, 0 to 5395
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   brand            5296 non-null   str
 1   model            5296 non-null   str
 2   generation       5290 non-null   str
 3   year             5296 non-null   int64
 4   city             5296 non-null   str
 5   body_type        5296 non-null   str
 6   fuel_type        5296 non-null   str
 7   engine_volume    5296 non-null   float64
 8   mileage          5296 non-null   int64
 9   transmission     5296 non-null   str
 10  drive_type       5296 non-null   str
 11  steering_wheel   5296 non-null   str
 12  color            5296 non-null   str
 13  kz_registration  5296 non-null   str
 14  imgs_count       5296 non-null   int64
 15  price            5296 non-null   int64
dtypes: float64(1), int64(4), str(11)
memory usage: 703.4 KB

In [46]:
df_table.to_csv('df_table.csv', index=False)

### Выгрузим датасет для задачи на неструктурированных данных (изображения)

Загрузим архив с изображениями

In [4]:
# https://stackoverflow.com/questions/25010369/wget-curl-large-file-from-google-drive
!mkdir -p data/images
!gdown "https://drive.google.com/uc?export=download&id=1SirF1kI6C_vv6CekGxfm3w1fS34Nf0n3" -O data/images.zip
!unzip -q data/images.zip -d data/images
!rm -f data/images.zip

Downloading...
From (original): https://drive.google.com/uc?id=1SirF1kI6C_vv6CekGxfm3w1fS34Nf0n3
From (redirected): https://drive.google.com/uc?id=1SirF1kI6C_vv6CekGxfm3w1fS34Nf0n3&confirm=t&uuid=89e8cf30-a77b-40f8-9a55-e8d4d778bb77
To: /Users/ksa/CodeProjects/gp_5_DL/data/images.zip
100%|███████████████████████████████████████| 234M/234M [00:13<00:00, 17.3MB/s]

Оставим в датасете только те строки, на которые есть изображения, которые мы только что скачали

In [47]:
import os

images = os.listdir('data/images')
print(f'Всего изображений: {len(images)}')

Всего изображений: 4993

In [48]:
df_images = df.copy()
df_images = df_images[(df_images['found_img'] == True) & (df_images['img_filename'].isin(images))]
df_images = df_images[['kolesa_id', 'brand', 'body_type', 'img_filename']]
df_images

      kolesa_id      brand    body_type    img_filename
0     220599328  Chevrolet        Седан  220599328.webp
1     222486528  Chevrolet        Седан  222486528.webp
2     218695550  Chevrolet  Внедорожник  218695550.webp
3     220471159  Chevrolet      Хэтчбек  220471159.webp
4     214781208  Chevrolet        Седан  214781208.webp
...         ...        ...          ...             ...
5390  222478046    Hyundai        Седан  222478046.webp
5391  222704181    Hyundai        Седан  222704181.webp
5392  220000872    Hyundai        Седан  220000872.webp
5394  222542135    Hyundai        Седан  222542135.webp
5395  220019907    Hyundai    Кроссовер  220019907.webp

[4965 rows x 4 columns]

In [49]:
df_images.to_csv('df_images.csv', index=False)

In [50]:
df_images['body_type'].value_counts()

body_type
Седан           2790
Кроссовер       1157
Внедорожник      487
Хэтчбек          148
Минивэн          118
Универсал        112
Лифтбек           36
Купе              32
Фургон            32
Пикап             15
Микроавтобус      15
Микровэн          13
Кабриолет          6
Родстер            4
Name: count, dtype: int64

In [51]:
df_images['brand'].value_counts()

brand
Mercedes-Benz    640
Lexus            636
Toyota           634
BMW              629
Kia              628
Hyundai          614
Audi             597
Chevrolet        587
Name: count, dtype: int64